"""
left_pipeline
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum

import path

"""
Write your markdown here…
| Format | Suffix | Description |
|:--|:--|:--|
| Avro | .avro | Binary file format for storage and serialization |
| Parquet | .parquet | Columnar storage file format  |
| ORC | .orc | Optimized Row Columnar file format |
"""

@aql.dataframe(task_id="root_node")
def root_node_func():
    import path

@dag(
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-04-14", "YYYY-MM-DD").in_tz("UTC"),
)
def left_pipeline():
    root_node = root_node_func()

dag_obj = left_pipeline()
